[package]
name = "fuck_webp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.21.0"
winit = "0.28.5"
egui_winit_platform = "0.18.0"
image = "0.24.6"
anyhow = "1.0.71"